### PR TITLE
Full Windows Support For Cookbook

### LINKED ISSUE #88: Basic support for windows platform
### Cookbook version
0.55.0

### Chef-client version
All

### Platform Details
Windows

### Scenario:
Installing and configuring a habitat package running on windows.

### Steps to Reproduce:
- Pick a windows hab package
- `hab_package 'pkg'` on a compatible windows package

### Expected Result:

Should download and install the latest version of the windows habitat package.

### Actual Result:
Errors out on `clean_array` from [`Chef::Mixin::ShellOut`](https://github.com/chef/chef/blob/master/lib/chef/mixin/shell_out.rb).

Passing the array to `shell_out_with_timeout!` was the problem, on windows when you try to execute this you get the following error:

```
NoMethodError
-------------
undefined method `each_char' for ["hab", "pkg", "path", "skylerto/splunkforwarder"]:Array
Did you mean?  each
    each_cons
```

and debug stacktrace:

```
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout/windows.rb:266:in `should_run_under_cmd?'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout/windows.rb:191:in `command_to_run'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout/windows.rb:59:in `run_command'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/mixin/shell_out.rb:191:in `shell_out_command'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/mixin/shell_out.rb:112:in `shell_out'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/mixin/shell_out.rb:117:in `shell_out!'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider/package.rb:637:in `shell_out_with_timeout!'
  C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:90:in `hab'
  C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:144:in `installed_version'
  C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:139:in `block in current_versions'
  C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:138:in `map'
  C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:138:in `current_versions'
  C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/habitat/libraries/provider_hab_package.rb:59:in `load_current_resource'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:128:in `run_action'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `each'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:96:in `converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:710:in `catch'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:710:in `converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:286:in `run'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:59:in `run'
  C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/bin/chef-client:26:in `<top (required)>'
  C:/opscode/chef/bin/chef-client:68:in `load'
  C:/opscode/chef/bin/chef-client:68:in `<main>'
```

### PR DESCRIPTION
**Pull request by wduncanfraser**
### Description

This PR introduces full windows support to the cookbook, with the exception of running multiple different supervisors, due to the limitation of using the windows-service package (which is the recommended production workflow).

Changelog

* Added full windows support
* Fixed bug introduced by transition to remote_sup cli option. Needed an additional property to specify the http port for the supervisor
* Moved version pins and shared code into habitat_shared library to reduce duplication of code

Note: I tested with an internal windows-2016 image. I changed this to the same chef image that is used in chef-client and other cookbooks that support windows.

~This is dependent on #140~ 

### Issues Resolved

This closes #88 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by jkerry** [comment]
We at NCR love to see this get through. @wduncanfraser could you handle those merge conflicts?

File: libraries/provider_hab_package.rb [hunk 1]
```diff
@@ -155,7 +148,9 @@ def current_versions
         end
 
         def installed_version(ident)
-          hab('pkg', 'path', ident).stdout.chomp.split('/')[-2..-1].join('/')
+          # Handling windows vs linux pathing
+          seperator = platform_family?('windows') ? '\\' : '/'
```
Comment (lamont-granquist) [inline libraries/provider_hab_package.rb]: should be spelled separator.  also this can be replaced with `File.ALT_SEPARATOR`.

you might consider this, although I'm not certain its any clearer:

```
[7] pry(main)> file = "/foo/bar/baz/fizz/buzz"
=> "/foo/bar/baz/fizz/buzz"
[8] pry(main)> File.join(File.basename(File.dirname(file)), File.basename(file))
=> "fizz/buzz"
```

File.basename + File.dirname should DTRT when it comes to the ALT_SEPARATOR on windows.

File: libraries/habitat_shared.rb [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    end
+
+    def hab(*command)
+      # Windows shell_out does not support arrays, so manually cleaning and joining
+      hab_cmd = (['hab'] + command).flatten.compact.join(' ')
+
+      if Gem::Requirement.new('>= 14.3.20').satisfied_by?(Gem::Version.new(Chef::VERSION))
+        shell_out!(hab_cmd)
+      else
+        shell_out_with_timeout!(hab_cmd)
```
Comment (lamont-granquist) [inline libraries/habitat_shared.rb]: this probably needs to be `shell_out_compact_timeout!`

**Comment by wduncanfraser** [comment]
Will be looking into this, been out of town so sorry for the delay.

File: libraries/provider_hab_package.rb (hunk 1 above)
Comment (wduncanfraser) [reply libraries/provider_hab_package.rb]: During my rebase this bit of code got replaced by changes from #148

File: libraries/habitat_shared.rb (hunk 2 above)
Comment (wduncanfraser) [reply libraries/habitat_shared.rb]: Made this change

**Comment by wduncanfraser** [comment]
@lamont-granquist @jkerry I've rebased, resolved conflicts, and squashed. Additionally, I made the changes @lamont-granquist requested.

**Comment by lamont-granquist** [comment]
i'm good with the changes i request, but someone with more windows background should really look at this.

File: libraries/habitat_shared.rb [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+      end
+    end
+
+    def hab_windows_service_version
+      WINDOWS_SERVICE_VERSION
+    end
+
+    def hab(*command)
+      # Windows shell_out does not support arrays, so manually cleaning and joining
+      hab_cmd = (['hab'] + command).flatten.compact.join(' ')
```
Comment (lamont-granquist) [inline libraries/habitat_shared.rb]: actually this should probably only be done on windows.  there's benefits on the unix-side to passing through the array version since then strings-with-spaces don't need to be quoted.

still since we can't do this on windows that means that every argument which could be a file-with-spaces ("C:\Program Files" trivially triggers these bugs) needs to be quoted.

File: resources/config.rb [hunk 4]
```diff
@@ -24,10 +24,12 @@
          coerce: proc { |m| m.is_a?(Hash) ? Mash.new(m) : m }
 property :service_group, String, name_property: true, desired_state: false
 property :remote_sup, String, default: '127.0.0.1:9632', desired_state: false
+# Http port needed for querying/comparing current config value
+property :remote_sup_http, String, default: '127.0.0.1:9631', desired_state: false
```
Comment (tas50) [inline resources/config.rb]: Not that it needs to be done here, but at some point we should get some validation on the input here

File: libraries/habitat_shared.rb (hunk 3 above)
Comment (lamont-granquist) [reply libraries/habitat_shared.rb]: (i'm less concerned with fixing every last issue in the latter case since going from no-windows support to some-bugs-in-windows support is still progress, but the unix API shouldn't go backwards in the process)

Comment (wduncanfraser) [reply libraries/habitat_shared.rb]: @lamont-granquist I made the assignment of hab_cmd conditional on platform

**Comment by jonlives** [comment]
Resolved merge conflicts from other merged PRs, will get this merged too once tests pass and cut a new release. Thanks for all the work on this!

**Comment by jonlives** [comment]
Merging now, some issues I need to fix on a branch I have access to. As soon as that's done, will push new version.
